apiVersion: v1
kind: Service
metadata:
  name: quote-gen-service-loadbalancer
spec:
  selector:
    app: quote-gen-service
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 4002
    targetPort: 5002
    nodePort: 31112