apiVersion: v1
kind: Service
metadata:
  name: user-like-service-loadbalancer
spec:
  selector:
    app: user-like-service 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 4001
    targetPort: 5001
    nodePort: 31111